preload = /home/graham/local/wallpapers/2026/dark/pexels-catiamatos-1072179.jpg


wallpaper {
    monitor = eDP-1
    path = /home/graham/local/wallpapers/2026/dark/pexels-catiamatos-1072179.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/graham/local/wallpapers/2026/dark/pexels-catiamatos-1072179.jpg
    fit_mode = cover
}

splash = false
ipc = true
