
monitor=eDP-1,preferred,auto,1.33

decoration {
    rounding = 5

    # Change transparency of focused and unfocused windows
    active_opacity = 0.80
    inactive_opacity = 0.80
    fullscreen_opacity = 0.80
}

device {
    name = tpps/2-elan-trackpoint
    sensitivity = -0.30
    accel_profile = adaptive
}

# expose ${HOSTNAME} to the environment
env = HOSTNAME, thinktop
